### PR TITLE
Folders 19 and 20 have out of date main.js

### PR DESCRIPTION
**Pull request by chadfawcett**
The animations were added in video 19, so the animations should be present in folder 20.

### CODE REVIEW

**Comment by chadfawcett** [comment]
Looks like the animations are in folder 19 for some reason. The folders are supposed to reflect the code at the beginning of the video is it not?

I'll do another commit later tonight to fix folder 19.

**Comment by chadfawcett** [comment]
Have updated folder 19 to not have the animations in main.js as they aren't there at the beginning of the video.

**Comment by chadfawcett** [comment]
@wesbos Any thoughts on this?

**Comment by wesbos** [comment]
Closing as I've replaced everything with updated files

**Pull request closed without merging**
