### PR TITLE
added note re. max. node major version <= 11 due to grpc-node

### PR DESCRIPTION
**Pull request by fnl**
see readme.md diff

### CODE REVIEW

**Comment by piazzamp** [comment]
it may also make sense to update the firebase package version (though it's 2 major versions off so unsure of the impact)

**Comment by wesbos** [comment]
Thanks - I think it would be worth figuring out what uses `gprc-node` and update that. Is it the firebase dep?

**Comment by piazzamp** [comment]
yeah I think I ran `npm tree` and followed it up to firebase/app. the latest version has been working without issue for me so far :)

**Comment by wesbos** [comment]
thanks folks! Looks like the firebase API for 7 works with re-base. It throws a peer dep warning, but no issues arise from it. Just upgraded it so you can now use this with the latest node :)

**Pull request closed without merging**
