### PR TITLE
Styling for total in order col

### PR DESCRIPTION
**Pull request by domgaulton**
Total price now right aligned and looks like <li> element given that it is now a div

### CODE REVIEW

**Comment by domgaulton** [comment]
Forgot to add reviewers but would love to get a PR to this! @paulschreiber @rclanan  @vladikoff  @wesbos

**Comment by autoboxer** [comment]
@domgaulton, although I'm not a reviewer, I tested it out and it looks good.  I do think, however, that this PR is incomplete.  You haven't run `npm run styles` to update the compiled **style.css** file, which should be checked in as well.  In addition, for continuity of the course, it would be a good idea to go through the **stepped-solution/** directory and make the same change, as well as run `npm run styles` in each.

**Comment by domgaulton** [comment]
Annoyingly the `autoprefixer-stylus` is not compling `box-sizing` like it did on the previous version however I have gone through each `style.styl` changed file and compiled it and pushed the changes in the latest PR @paulschreiber @rclanan @vladikoff @wesbos

**Comment by wesbos** [comment]
thanks a ton!

**Comment by domgaulton** [comment]
You’re welcome!

Big fan so this has made my evening!

Merry Christmas from the UK!

Dom Gaulton

**Pull request merged**
